"""Autowiring against six real ComfyUI API-format graphs.

Fixtures in ``fixtures/comfy/`` are verbatim exports with long string literals
replaced by ``<text N chars>`` placeholders — only the graph topology matters here.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict

import pytest

from offloadmq_core.comfy_autowire import (
    _Unresolved,
    guess_params_ex,
    live_subgraph,
    node_order,
    resolve_literal,
)

FIXTURES = Path(__file__).parent / "fixtures" / "comfy"


def load(name: str) -> Dict[str, Any]:
    with open(FIXTURES / f"{name}.json", encoding="utf-8") as f:
        graph: Dict[str, Any] = json.load(f)
    return graph


# --------------------------------------------------------------------------
# Graph primitives
# --------------------------------------------------------------------------


def test_node_order_sorts_ints_numerically_then_composites() -> None:
    assert node_order(["103:17", "9", "114", "103:8", "62"]) == [
        "9",
        "62",
        "114",
        "103:17",
        "103:8",
    ]


def test_live_subgraph_excludes_preview_only_branches() -> None:
    graph = load("longcat_redraw")
    live = live_subgraph(graph)
    # 20 is PreviewAny — a dead end hanging off the Ollama node.
    assert "20" not in live
    # 13:8 (VAEDecode) feeds SaveImage; 19 (Ollama) feeds the positive encoder.
    assert {"9", "13:8", "13:7", "19"} <= live


def test_live_subgraph_falls_back_to_whole_graph_without_output_node() -> None:
    graph = {"1": {"class_type": "PreviewImage", "inputs": {}}}
    assert live_subgraph(graph) == {"1"}


def test_live_subgraph_drops_dead_preview_image_branch() -> None:
    graph = load("wan_i2v")
    live = live_subgraph(graph)
    assert "127" not in live  # PreviewImage
    assert "118" not in live  # PreviewAny


# --------------------------------------------------------------------------
# resolve_literal
# --------------------------------------------------------------------------


def test_resolve_literal_returns_direct_literal() -> None:
    graph = load("kandinsky_t2v")
    assert resolve_literal(graph, "12:8", "seed") == ("12:8", "seed")


def test_resolve_literal_follows_primitive_int_indirection() -> None:
    graph = load("ace_step")
    # KSampler.seed is wired to PrimitiveInt "109" — writing it directly would
    # sever the wire.
    assert resolve_literal(graph, "3", "seed") == ("109", "value")


def test_resolve_literal_rejects_derived_size() -> None:
    graph = load("capybara_edit")
    with pytest.raises(_Unresolved, match="GetImageSize"):
        resolve_literal(graph, "103:78", "width")


def test_resolve_literal_rejects_generated_text() -> None:
    graph = load("longcat_redraw")
    with pytest.raises(_Unresolved, match="OllamaGenerateV2"):
        resolve_literal(graph, "13:4", "text")


def test_resolve_literal_rejects_concat_of_generated_text() -> None:
    graph = load("capybara_i2v")
    # 103:44.text ← StringConcatenate(129) ← OllamaGenerateV2(128)
    with pytest.raises(_Unresolved, match="StringConcatenate"):
        resolve_literal(graph, "103:44", "text")


def test_resolve_literal_rejects_missing_input() -> None:
    graph = load("kandinsky_t2v")
    with pytest.raises(_Unresolved, match="no input"):
        resolve_literal(graph, "12:8", "nonexistent")


# --------------------------------------------------------------------------
# wan_i2v — WanImageToVideo, two-stage KSamplerAdvanced, ReActor face swap
# --------------------------------------------------------------------------


def test_wan_i2v() -> None:
    params, notes = guess_params_ex(load("wan_i2v"), "img2video")

    # The old slot-blind trace walked into WanImageToVideo(63) and returned the
    # *positive* encoder for the negative wire ["63", 1]; negative was then dropped.
    assert params["negative"] == [["7", "text"]]

    # 62 is the scene image (→ ReActor.input_image → WanImageToVideo.start_image);
    # 126 is the ReActor face reference.
    assert params["input_image"] == [["62", "image"]]
    assert params["face_swap"] == [["126", "image"]]

    # 58 has add_noise: "disable" — its noise_seed never affects the output.
    assert params["seed"] == [["57", "noise_seed"]]

    assert params["steps"] == [["57", "steps"], ["58", "steps"]]
    assert params["cfg"] == [["57", "cfg"], ["58", "cfg"]]
    assert params["width"] == [["63", "width"]]
    assert params["height"] == [["63", "height"]]
    assert params["length"] == [["63", "length"]]
    assert params["fps"] == [["109", "fps"]]

    # The positive prompt is generated by an Ollama chain — nothing to overwrite.
    assert params["prompt"] == []
    assert "129" in notes["prompt"]


# --------------------------------------------------------------------------
# capybara_i2v — SamplerCustomAdvanced + CFGGuider + PrimitiveInt size nodes
# --------------------------------------------------------------------------


def test_capybara_i2v() -> None:
    params, notes = guess_params_ex(load("capybara_i2v"), "img2video")

    # HunyuanVideo15ImageToVideo.width/height are wires into PrimitiveInt nodes.
    assert params["width"] == [["103:121", "value"]]
    assert params["height"] == [["103:122", "value"]]

    # KSamplerSelect must not be mistaken for a sampler: the seed lives on RandomNoise.
    assert params["seed"] == [["103:25", "noise_seed"]]
    assert params["steps"] == [["103:17", "steps"]]
    assert params["cfg"] == [["103:91", "cfg"]]
    assert params["fps"] == [["103:113", "fps"]]

    assert params["input_image"] == [["126", "image"]]
    assert params["negative"] == [["103:93", "text"]]
    assert params["length"] == [["103:115", "length"]]

    assert params["prompt"] == []
    assert "StringConcatenate" in notes["prompt"]


# --------------------------------------------------------------------------
# kandinsky_t2v — the happy path: everything is a literal
# --------------------------------------------------------------------------


def test_kandinsky_t2v() -> None:
    params, notes = guess_params_ex(load("kandinsky_t2v"), "txt2video")

    assert params["prompt"] == [["12:7", "text"]]
    assert params["negative"] == [["12:2", "text"]]
    assert params["width"] == [["12:5", "width"]]
    assert params["height"] == [["12:5", "height"]]
    assert params["length"] == [["12:5", "length"]]
    assert params["seed"] == [["12:8", "seed"]]
    assert params["steps"] == [["12:8", "steps"]]
    assert params["cfg"] == [["12:8", "cfg"]]
    assert params["fps"] == [["12:10", "fps"]]
    assert notes == {}


# --------------------------------------------------------------------------
# capybara_edit — img2img whose size is derived from the input image
# --------------------------------------------------------------------------


def test_capybara_edit() -> None:
    params, notes = guess_params_ex(load("capybara_edit"), "img2img")

    assert params["input_image"] == [["80", "image"]]
    assert params["seed"] == [["103:25", "noise_seed"]]
    assert params["prompt"] == [["103:44", "text"]]
    assert params["negative"] == [["103:93", "text"]]

    # width/height come from GetImageSize(103:98) — writing them is a silent no-op.
    assert params["width"] == []
    assert params["height"] == []
    assert "GetImageSize" in notes["width"]
    assert "GetImageSize" in notes["height"]

    # img2img has no frame count.
    assert "length" not in params


# --------------------------------------------------------------------------
# longcat_redraw — both encoders share the title "CLIP Text Encode (Prompt)",
# so only graph tracing can tell positive from negative.
# --------------------------------------------------------------------------


def test_longcat_redraw() -> None:
    params, notes = guess_params_ex(load("longcat_redraw"), "txt2img")

    assert params["negative"] == [["13:5", "text"]]

    assert params["prompt"] == []
    assert "OllamaGenerateV2" in notes["prompt"]

    # EmptySD3LatentImage.width/height ← ResolutionSelector.
    assert params["width"] == []
    assert params["height"] == []
    assert "ResolutionSelector" in notes["width"]

    assert params["seed"] == [["13:7", "seed"]]
    assert params["cfg"] == [["13:7", "cfg"]]


# --------------------------------------------------------------------------
# ace_step — txt2music
# --------------------------------------------------------------------------


def test_ace_step() -> None:
    params, notes = guess_params_ex(load("ace_step"), "txt2music")

    # Both KSampler.seed and TextEncodeAceStepAudio1.5.seed wire into PrimitiveInt(109).
    assert params["seed"] == [["109", "value"]]

    assert params["duration"] == [["94", "duration"], ["98", "seconds"]]
    assert params["tags"] == [["94", "tags"]]
    assert params["lyrics"] == [["94", "lyrics"]]
    assert params["bpm"] == [["94", "bpm"]]
    assert params["keyscale"] == [["94", "keyscale"]]
    assert params["cfg_scale"] == [["94", "cfg_scale"]]
    assert params["steps"] == [["3", "steps"]]

    # txt2music has no prompt/negative concept.
    assert "prompt" not in params
    assert "negative" not in params
    assert notes == {}


# --------------------------------------------------------------------------
# Invariants that hold for every fixture
# --------------------------------------------------------------------------

_ALL = [
    ("wan_i2v", "img2video"),
    ("capybara_i2v", "img2video"),
    ("kandinsky_t2v", "txt2video"),
    ("capybara_edit", "img2img"),
    ("longcat_redraw", "txt2img"),
    ("ace_step", "txt2music"),
]


@pytest.mark.parametrize(("fixture", "task_type"), _ALL)
def test_every_target_is_an_existing_literal_slot(fixture: str, task_type: str) -> None:
    """No target may point at a missing node, a missing input, or a wired slot.

    Writing into a wired slot is what silently corrupts the graph at execution time.
    """
    graph = load(fixture)
    params, _ = guess_params_ex(graph, task_type)
    for field, targets in params.items():
        assert targets is not None
        for node_id, input_name in targets:
            assert node_id in graph, f"{field}: node {node_id} missing"
            inputs = graph[node_id]["inputs"]
            assert input_name in inputs, f"{field}: {node_id} has no input {input_name}"
            value = inputs[input_name]
            assert not isinstance(value, list), f"{field}: {node_id}.{input_name} is a wire"


@pytest.mark.parametrize(("fixture", "task_type"), _ALL)
def test_autodetect_is_deterministic(fixture: str, task_type: str) -> None:
    graph = load(fixture)
    first = guess_params_ex(graph, task_type)
    for _ in range(5):
        assert guess_params_ex(load(fixture), task_type) == first


@pytest.mark.parametrize(("fixture", "task_type"), _ALL)
def test_unresolved_fields_are_empty_and_explained(fixture: str, task_type: str) -> None:
    params, notes = guess_params_ex(load(fixture), task_type)
    for field, targets in params.items():
        if targets == []:
            assert field in notes, f"{field} is unwired but has no note"
        assert "FIXME" not in json.dumps(targets)
