//! Server-side `{placeholder}` expansion for prompts — a port of the web UI's
//! `frontend/src/lib/promptPlaceholders.ts`, used by callers that have no browser to
//! expand prompts for them (the MCP tools).
//!
//! - `{color}` `{animal}` `{adjective}` `{country}` `{language}` `{name}` `{starwars}`
//!   draw from the same `unique-names-generator` word lists as the web UI
//!   (`placeholder_dicts/*.txt`, regenerated by `scripts/gen-placeholder-dicts.mjs`).
//! - Any other `{name}` is one of the user's custom placeholders
//!   (`db::prompt_placeholders`); a picked variant is expanded again, up to
//!   [`MAX_PLACEHOLDER_DEPTH`] levels (which also stops cycles).
//! - `{?}` and unknown names are left untouched — `{?}` is expanded later, at job
//!   creation (`image_job_names::expand_prompt_placeholders`).
//!
//! One [`PromptExpander`] tracks the values it has handed out per placeholder name, so
//! expanding a batch of prompts through the same expander never repeats a value until
//! that dictionary or variant list is exhausted.

use std::{
    collections::{HashMap, HashSet},
    sync::OnceLock,
};

use rand::Rng;
use sea_orm::DatabaseConnection;

use crate::{db::prompt_placeholders, error::AppError};

/// Recursion cap for custom variants that contain placeholders themselves.
pub const MAX_PLACEHOLDER_DEPTH: usize = 5;
/// Match the prompt library's content limit, including unexpanded input.
pub const MAX_EXPANDED_PROMPT_BYTES: usize = 32_000;
/// Bound recursive work even when replacements produce little or no output.
const MAX_PLACEHOLDER_SUBSTITUTIONS: usize = 4_096;

/// Builtin categories, in the order the web UI lists them (alphabetical).
pub const BUILTIN_CATEGORIES: &[&str] = &[
    "adjective",
    "animal",
    "color",
    "country",
    "language",
    "name",
    "starwars",
];

fn builtin_dictionary(name: &str) -> Option<&'static [&'static str]> {
    static DICTS: OnceLock<HashMap<&'static str, Vec<&'static str>>> = OnceLock::new();
    let dicts = DICTS.get_or_init(|| {
        let raw: [(&str, &'static str); 7] = [
            ("adjective", include_str!("placeholder_dicts/adjective.txt")),
            ("animal", include_str!("placeholder_dicts/animal.txt")),
            ("color", include_str!("placeholder_dicts/color.txt")),
            ("country", include_str!("placeholder_dicts/country.txt")),
            ("language", include_str!("placeholder_dicts/language.txt")),
            ("name", include_str!("placeholder_dicts/name.txt")),
            ("starwars", include_str!("placeholder_dicts/starwars.txt")),
        ];
        raw.into_iter()
            .map(|(k, text)| {
                (
                    k,
                    text.lines()
                        .map(str::trim)
                        .filter(|l| !l.is_empty())
                        .collect(),
                )
            })
            .collect()
    });
    dicts.get(name).map(Vec::as_slice)
}

fn is_token_char(c: char) -> bool {
    c.is_ascii_alphanumeric() || matches!(c, '.' | '-' | '_')
}

pub struct PromptExpander {
    /// Lowercased custom placeholder name → variants.
    custom: HashMap<String, Vec<String>>,
    used: HashMap<String, HashSet<String>>,
}

impl PromptExpander {
    pub fn new(custom: impl IntoIterator<Item = (String, Vec<String>)>) -> Self {
        Self {
            custom: custom
                .into_iter()
                .map(|(name, variants)| (name.trim().to_lowercase(), variants))
                .collect(),
            used: HashMap::new(),
        }
    }

    /// An expander over the user's custom placeholders.
    pub async fn for_user(db: &DatabaseConnection, user_id: i64) -> Result<Self, AppError> {
        let rows = prompt_placeholders::list_for_user(db, user_id).await?;
        let mut custom = Vec::with_capacity(rows.len());
        for row in &rows {
            custom.push((row.name.clone(), prompt_placeholders::decode_variants(row)?));
        }
        Ok(Self::new(custom))
    }

    pub fn expand(&mut self, text: &str) -> Result<String, AppError> {
        if text.len() > MAX_EXPANDED_PROMPT_BYTES {
            return Err(prompt_size_error());
        }
        let mut out = String::with_capacity(text.len());
        let mut remaining = MAX_PLACEHOLDER_SUBSTITUTIONS;
        self.expand_level(text, 0, &mut out, &mut remaining)?;
        Ok(out)
    }

    // All recursion writes into one bounded buffer, so intermediate replacements
    // cannot grow exponentially before their size is checked.
    fn expand_level(
        &mut self,
        text: &str,
        depth: usize,
        out: &mut String,
        remaining: &mut usize,
    ) -> Result<(), AppError> {
        if !text.contains('{') || depth >= MAX_PLACEHOLDER_DEPTH {
            return push_bounded(out, text);
        }
        let mut rest = text;
        while let Some(open) = rest.find('{') {
            push_bounded(out, &rest[..open])?;
            let after = &rest[open + 1..];
            let token_len = after
                .find(|c: char| !is_token_char(c))
                .unwrap_or(after.len());
            if token_len > 0 && after[token_len..].starts_with('}') {
                *remaining = remaining.checked_sub(1).ok_or_else(|| {
                    AppError::BadRequest(format!(
                        "prompt expansion exceeds {MAX_PLACEHOLDER_SUBSTITUTIONS} substitutions"
                    ))
                })?;
                let token = &after[..token_len];
                if let Some(replacement) = self.resolve(token) {
                    self.expand_level(&replacement, depth + 1, out, remaining)?;
                } else {
                    push_bounded(out, &rest[open..open + token_len + 2])?;
                }
                rest = &after[token_len + 1..];
            } else {
                push_bounded(out, "{")?;
                rest = after;
            }
        }
        push_bounded(out, rest)
    }

    /// The replacement for `{token}`, or `None` to leave it as written.
    fn resolve(&mut self, token: &str) -> Option<String> {
        let key = token.to_lowercase();
        if let Some(dict) = builtin_dictionary(&key) {
            // Dictionary words contain no braces — no need to expand them again.
            return Some(pick_unique(dict, self.used.entry(key).or_default()));
        }
        let variants = self.custom.get(&key).filter(|v| !v.is_empty())?;
        Some(pick_unique(variants, self.used.entry(key).or_default()))
    }
}

fn prompt_size_error() -> AppError {
    AppError::BadRequest(format!(
        "prompt expansion exceeds {MAX_EXPANDED_PROMPT_BYTES} bytes"
    ))
}

fn push_bounded(out: &mut String, text: &str) -> Result<(), AppError> {
    if text.len() > MAX_EXPANDED_PROMPT_BYTES - out.len() {
        return Err(prompt_size_error());
    }
    out.push_str(text);
    Ok(())
}

/// A random entry not yet in `used` (bounded retries, like the web UI); once every
/// entry has been used, starts a fresh cycle instead of looping forever.
fn pick_unique<S: AsRef<str>>(pool: &[S], used: &mut HashSet<String>) -> String {
    if pool.is_empty() {
        return String::new();
    }
    if used.len() >= pool.len() {
        used.clear();
    }
    let mut rng = rand::rng();
    let mut value = pool[rng.random_range(0..pool.len())].as_ref();
    let mut guard = 1;
    while used.contains(value) && guard < pool.len().saturating_mul(4).min(64) {
        value = pool[rng.random_range(0..pool.len())].as_ref();
        guard += 1;
    }
    used.insert(value.to_string());
    value.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn expander(custom: &[(&str, &[&str])]) -> PromptExpander {
        PromptExpander::new(
            custom
                .iter()
                .map(|(n, v)| (n.to_string(), v.iter().map(|s| s.to_string()).collect())),
        )
    }

    #[test]
    fn every_builtin_category_has_words() {
        for cat in BUILTIN_CATEGORIES {
            let dict = builtin_dictionary(cat).expect(cat);
            assert!(dict.len() > 10, "{cat} has only {} entries", dict.len());
        }
        // The builtins are exactly the reserved names (minus `{?}`).
        let mut reserved: Vec<&str> = prompt_placeholders::RESERVED_PLACEHOLDER_NAMES
            .iter()
            .copied()
            .filter(|n| *n != "?")
            .collect();
        reserved.sort();
        assert_eq!(reserved, BUILTIN_CATEGORIES);
    }

    #[test]
    fn builtins_expand_case_insensitively() {
        let mut e = expander(&[]);
        let out = e.expand("a {Color} {ANIMAL}").unwrap();
        assert!(!out.contains('{'), "{out}");
        assert!(out.starts_with("a "));
    }

    #[test]
    fn question_mark_unknown_and_malformed_tokens_are_left_alone() {
        let mut e = expander(&[]);
        assert_eq!(
            e.expand("{?} {unknown} {} { color} {color").unwrap(),
            "{?} {unknown} {} { color} {color"
        );
    }

    #[test]
    fn nested_braces_match_the_inner_token_like_the_js_regex() {
        let mut e = expander(&[("x", &["X"])]);
        assert_eq!(e.expand("{{x}}").unwrap(), "{X}");
    }

    #[test]
    fn custom_variants_recurse_and_cycles_stop_at_the_depth_cap() {
        let mut e = expander(&[("outer", &["big {inner}"]), ("inner", &["cat"])]);
        assert_eq!(e.expand("a {outer}").unwrap(), "a big cat");

        let mut cyclic = expander(&[("a", &["<{b}>"]), ("b", &["[{a}]"])]);
        let out = cyclic.expand("{a}").unwrap();
        assert_eq!(out, "<[<[<{b}>]>]>");
    }

    #[test]
    fn a_batch_does_not_repeat_until_the_pool_is_exhausted() {
        let mut e = expander(&[("pet", &["cat", "dog", "fox"])]);
        let mut seen: Vec<String> = (0..3).map(|_| e.expand("{pet}").unwrap()).collect();
        seen.sort();
        assert_eq!(seen, vec!["cat", "dog", "fox"]);
        // Fourth draw starts a new cycle instead of hanging.
        assert!(["cat", "dog", "fox"].contains(&e.expand("{pet}").unwrap().as_str()));
    }

    #[test]
    fn repeated_tokens_in_one_prompt_get_distinct_values() {
        let mut e = expander(&[("pet", &["cat", "dog"])]);
        let out = e.expand("{pet}+{pet}").unwrap();
        assert!(out == "cat+dog" || out == "dog+cat", "{out}");
    }

    #[test]
    fn recursive_fanout_is_rejected_before_allocating_its_full_output() {
        let variant = "{x}".repeat(600);
        let mut e = expander(&[("x", &[&variant])]);
        let err = e.expand("{x}").unwrap_err();
        assert!(matches!(err, AppError::BadRequest(m) if m.contains("32000 bytes")));
    }

    #[test]
    fn expansion_limits_count_bytes_and_accept_the_exact_boundary() {
        let replacement = "é".repeat(1_000);
        let mut e = expander(&[("x", &[&replacement])]);
        assert_eq!(
            e.expand(&"{x}".repeat(16)).unwrap().len(),
            MAX_EXPANDED_PROMPT_BYTES
        );
        assert!(e.expand(&"{x}".repeat(17)).is_err());
        assert!(
            e.expand(&"a".repeat(MAX_EXPANDED_PROMPT_BYTES + 1))
                .is_err()
        );
    }

    #[test]
    fn substitution_work_is_bounded_even_with_small_replacements() {
        let branch = "{small}".repeat(250);
        let mut e = expander(&[("branch", &[&branch]), ("small", &["x"])]);
        let err = e.expand(&"{branch}".repeat(20)).unwrap_err();
        assert!(matches!(err, AppError::BadRequest(m) if m.contains("4096 substitutions")));
        // Budgets belong to an expansion, not to the expander's batch lifetime.
        assert_eq!(e.expand("{small}").unwrap(), "x");
    }
}
