// Shared style definitions for sandbox apps.
// Import and spread into per-app style objects to avoid duplication.

export const sandboxStyles = {
  content: {
    padding: '4px',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
  },
  row: {
    display: 'flex',
    gap: '16px',
  },
  label: {
    fontFamily: 'var(--font-display)',
    fontSize: '14px',
    fontWeight: '600',
    color: 'var(--text)',
    marginBottom: '6px',
  },
  labelRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '6px',
  },
  input: {
    fontFamily: 'var(--font-sans)',
    padding: '8px 12px',
    fontSize: '14px',
    border: '1px solid var(--border)',
    borderRadius: '6px',
    outline: 'none',
    background: 'var(--input-bg)',
    color: 'var(--text)',
  },
  monoInput: {
    padding: '8px 12px',
    fontSize: '14px',
    border: '1px solid var(--border)',
    borderRadius: '6px',
    outline: 'none',
    fontFamily: 'monospace',
    background: 'var(--input-bg)',
    color: 'var(--text)',
  },
  textarea: {
    fontFamily: 'var(--font-sans)',
    padding: '8px 12px',
    fontSize: '14px',
    border: '1px solid var(--border)',
    borderRadius: '6px',
    resize: 'vertical',
    outline: 'none',
    background: 'var(--input-bg)',
    color: 'var(--text)',
  },
  button: {
    fontFamily: 'var(--font-sans)',
    padding: '10px 16px',
    fontSize: '14px',
    fontWeight: '600',
    color: '#FFF',
    backgroundColor: '#007AFF',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    alignSelf: 'flex-start',
  },
  greenButton: {
    fontFamily: 'var(--font-sans)',
    padding: '10px 16px',
    fontSize: '14px',
    fontWeight: '600',
    color: '#FFF',
    backgroundColor: '#28A745',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    alignSelf: 'flex-start',
  },
  responseContainer: {
    marginTop: '24px',
    padding: '16px',
    background: 'var(--glass)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
  },
  responseLabel: {
    fontFamily: 'var(--font-display)',
    fontSize: '14px',
    fontWeight: '600',
    color: 'var(--text)',
    margin: '0 0 12px 0',
  },
  loading: {
    fontFamily: 'var(--font-sans)',
    color: 'var(--muted)',
    fontStyle: 'italic',
  },
  response: {
    fontFamily: 'var(--font-sans)',
    whiteSpace: 'pre-wrap',
    wordWrap: 'break-word',
    fontSize: '12px',
    color: 'var(--text)',
    margin: '0',
  },
  error: {
    fontFamily: 'var(--font-sans)',
    whiteSpace: 'pre-wrap',
    wordWrap: 'break-word',
    fontSize: '12px',
    color: 'var(--danger)',
    margin: '0',
  },
  terminal: {
    backgroundColor: '#000000',
    padding: '12px',
    borderRadius: '4px',
    border: '1px solid #333',
    fontFamily: 'Consolas, Monaco, "Courier New", monospace',
    fontSize: '13px',
    lineHeight: '1.4',
  },
  toggleBtn: {
    fontFamily: 'var(--font-sans)',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '12px',
    color: 'var(--primary)',
    padding: '0',
  },
  defaultHint: {
    fontFamily: 'var(--font-sans)',
    fontSize: '13px',
    color: 'var(--muted)',
    fontStyle: 'italic',
  },
  imageGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(256px, 1fr))',
    gap: '12px',
    marginBottom: '12px',
  },
  image: {
    width: '100%',
    borderRadius: '8px',
    border: '1px solid var(--border)',
    cursor: 'zoom-in',
  },
  imageFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: '6px',
  },
  imageName: {
    fontFamily: 'var(--font-sans)',
    fontSize: '12px',
    color: 'var(--muted)',
    margin: '0',
    wordBreak: 'break-all',
  },
  downloadLink: {
    fontFamily: 'var(--font-sans)',
    fontSize: '12px',
    color: 'var(--primary)',
    textDecoration: 'none',
    flexShrink: 0,
    marginLeft: '8px',
  },
  seedInfo: {
    fontFamily: 'var(--font-sans)',
    fontSize: '12px',
    color: 'var(--muted)',
    margin: '8px 0 0 0',
  },
};
