import { Activity, Bot, Braces, Clapperboard, Eye, FolderOpen, GitCompareArrows, ImagePlus, MessageCircleMore, Music, ShieldAlert, Volume2, Wand2 } from 'lucide-react'

/** Every app tile on the dashboard; also the source for the TopBar's most-used shortcuts. */
export const apps = [
  {
    id: 'chat',
    icon: Bot,
    title: 'LLM Chat',
    description: 'Chat with AI models',
    href: '/app/chat',
    gradient: 'from-indigo-500/20 to-violet-500/20',
    iconBg: 'bg-indigo-500/20',
    iconColor: 'text-indigo-400',
  },
  {
    id: 'image-generation',
    icon: ImagePlus,
    title: 'Image Generation',
    description: 'Txt2Img and Img2Img with tracked pipeline',
    href: '/app/images',
    gradient: 'from-emerald-500/20 to-cyan-500/20',
    iconBg: 'bg-emerald-500/20',
    iconColor: 'text-emerald-400',
  },
  {
    id: 'describe',
    icon: Eye,
    title: 'Describe Image',
    description: 'Analyze images with vision AI',
    href: '/app/describe',
    gradient: 'from-sky-500/20 to-cyan-500/20',
    iconBg: 'bg-sky-500/20',
    iconColor: 'text-sky-400',
  },
  {
    id: 'img-utils',
    icon: Wand2,
    title: 'Image Tools',
    description: 'One-shot transforms: depth maps, face swap — image in, image out',
    href: '/app/img-utils',
    gradient: 'from-cyan-500/20 to-blue-500/20',
    iconBg: 'bg-cyan-500/20',
    iconColor: 'text-cyan-400',
  },
  {
    id: 'nude-detect',
    icon: ShieldAlert,
    title: 'Nude Detector',
    description: 'NSFW detection with NudeNet and tunable threshold',
    href: '/app/nude-detect',
    gradient: 'from-rose-500/20 to-orange-500/20',
    iconBg: 'bg-rose-500/20',
    iconColor: 'text-rose-400',
  },
  {
    id: 'runners',
    icon: Activity,
    title: 'Runners',
    description: 'View active OffloadMQ runner nodes',
    href: '/app/runners',
    gradient: 'from-teal-500/20 to-emerald-500/20',
    iconBg: 'bg-teal-500/20',
    iconColor: 'text-teal-400',
  },
  {
    id: 'music',
    icon: Music,
    title: 'Music Generation',
    description: 'Generate music from style tags and lyrics with txt2music models',
    href: '/app/music',
    gradient: 'from-fuchsia-500/20 to-pink-500/20',
    iconBg: 'bg-fuchsia-500/20',
    iconColor: 'text-fuchsia-400',
  },
  {
    id: 'tts',
    icon: Volume2,
    title: 'Text to Speech',
    description: 'Synthesize text as audio with Kokoro and other TTS models',
    href: '/app/tts',
    gradient: 'from-violet-500/20 to-fuchsia-500/20',
    iconBg: 'bg-violet-500/20',
    iconColor: 'text-violet-400',
  },
  {
    id: 'files',
    icon: FolderOpen,
    title: 'My Files',
    description: 'Browse your uploads and generated files',
    href: '/app/files',
    gradient: 'from-amber-500/20 to-orange-500/20',
    iconBg: 'bg-amber-500/20',
    iconColor: 'text-amber-400',
  },
  {
    id: 'llm-compare',
    icon: GitCompareArrows,
    title: 'LLM Compare',
    description: 'Run the same prompt on multiple models in parallel',
    href: '/app/llm-compare',
    gradient: 'from-sky-500/20 to-indigo-500/20',
    iconBg: 'bg-sky-500/20',
    iconColor: 'text-sky-400',
  },
  {
    id: 'llm-debate',
    icon: MessageCircleMore,
    title: 'LLM Debate',
    description: 'Two models debate turn by turn with an optional referee',
    href: '/app/llm-debate',
    gradient: 'from-emerald-500/20 to-teal-500/20',
    iconBg: 'bg-emerald-500/20',
    iconColor: 'text-emerald-400',
  },
  {
    id: 'movie',
    icon: Clapperboard,
    title: 'Movie Studio',
    description: 'Generate a multi-scene AI film from one idea',
    href: '/app/movie',
    gradient: 'from-rose-500/20 to-amber-500/20',
    iconBg: 'bg-rose-500/20',
    iconColor: 'text-rose-400',
  },
  {
    id: 'prompt-placeholders',
    icon: Braces,
    title: 'Prompt Placeholders',
    description: 'Manage your custom, recursive prompt placeholders',
    href: '/app/prompt-placeholders',
    gradient: 'from-purple-500/20 to-indigo-500/20',
    iconBg: 'bg-purple-500/20',
    iconColor: 'text-purple-400',
  },
] as const
