apiVersion: v1
kind: Secret
metadata:
  name: offloadmq-secrets
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  CLIENT_API_KEYS: {{ .Values.secrets.CLIENT_API_KEYS | quote }}
  AGENT_API_KEYS: {{ .Values.secrets.AGENT_API_KEYS | quote }}
