apiVersion: v1
kind: Service
metadata:
  name: offloadmq
spec:
  clusterIP: None # Required for stable network identity in StatefulSet
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: offloadmq
