replicaCount: 1

image:
  repository: your-docker-registry/offloadmq-frontend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

backend:
  apiUrl: http://offloadmq.offloadmq.svc.cluster.local:3069
  managementUrl: http://offloadmq.offloadmq.svc.cluster.local:3069
