"""Orchestrator API contract for the UI server."""
from __future__ import annotations

from collections.abc import Sequence
from typing import Any, Protocol

from pydantic import BaseModel


class OrchestratorAPI(Protocol):
    def get_settings(self) -> BaseModel: ...
    def update_settings(self, **fields: Any) -> BaseModel: ...
    def apply_settings(self, **fields: Any) -> BaseModel: ...
    def get_raw_settings_json(self) -> str: ...
    def save_raw_settings_json(self, text: str) -> BaseModel: ...

    def scan_capabilities(self) -> list[str]: ...
    def get_scan_state(self) -> dict[str, Any]: ...
    def start_background_scan(self) -> None: ...
    def rescan(self, *, restart_if_changed: bool = False) -> dict[str, Any]: ...
    def update_capability_policy(
        self,
        *,
        regular_disabled: list[str] | None = None,
        sensitive_allowed: list[str] | None = None,
        slavemode_allowed: list[str] | None = None,
    ) -> BaseModel: ...

    def start(self) -> None: ...
    def stop(self) -> None: ...
    def is_running(self) -> bool: ...
    def status(self) -> dict[str, Any]: ...
    def get_agent_logs(self, n: int = 100) -> list[str]: ...
    def register(self) -> str: ...

    def list_tasks(self) -> Sequence[BaseModel]: ...
    def get_task(self, task_id: str) -> BaseModel | None: ...
    def cancel_task(self, task_id: str) -> bool: ...

    def get_auto_update_status(self) -> dict[str, Any]: ...
    def trigger_auto_update(self) -> bool: ...

    # Custom capabilities
    def list_custom_caps(self) -> list[dict[str, Any]]: ...
    def get_custom_cap(self, name: str) -> str: ...
    def save_custom_cap(self, name: str, yaml_text: str) -> None: ...
    def delete_custom_cap(self, name: str) -> None: ...

    # ComfyUI workflows / param maps
    def list_comfy_workflows(self) -> dict[str, Any]: ...
    def add_comfy_workflow(
        self, workflow_name: str, task_type: str, namespace: str, graph_json: str
    ) -> None: ...
    def delete_comfy_workflow(self, workflow_name: str, namespace: str = "") -> None: ...
    def rename_comfy_workflow(
        self, workflow_name: str, namespace: str, new_workflow_name: str, new_namespace: str
    ) -> None: ...
    def duplicate_comfy_workflow(
        self, workflow_name: str, namespace: str, new_workflow_name: str, new_namespace: str
    ) -> None: ...
    def get_comfy_workflow_graph(
        self, workflow_name: str, task_type: str, namespace: str = ""
    ) -> str: ...
    def get_comfy_param_map(
        self, workflow_name: str, task_type: str, namespace: str = ""
    ) -> dict[str, Any]: ...
    def save_comfy_param_map(
        self, workflow_name: str, task_type: str, namespace: str, params: Any
    ) -> None: ...
    def autodetect_comfy_param_map(
        self, workflow_name: str, task_type: str, namespace: str
    ) -> dict[str, Any]: ...

    # Agent-managed ComfyUI server
    def startup_comfy(self) -> None: ...
    def comfy_process_status(self) -> dict[str, Any]: ...
    def comfy_process_action(self, action: str) -> dict[str, Any]: ...
    def detect_comfy_install(self) -> dict[str, Any] | None: ...

    # Updates
    def check_update(self) -> dict[str, Any]: ...
    def download_update(self) -> dict[str, Any]: ...

    # System / OS integration
    def get_startup_status(self) -> dict[str, Any]: ...
    def set_keep_awake(self, enable: bool) -> BaseModel: ...
    def set_pause_on_battery(self, enable: bool) -> BaseModel: ...
    def set_win_startup(self, enable: bool) -> BaseModel: ...
    def set_mac_startup(self, enable: bool) -> BaseModel: ...
    def install_systemd(self, host: str | None = None, port: int | None = None) -> dict[str, Any]: ...
    def uninstall_systemd(self) -> dict[str, Any]: ...
    def sync_keep_awake_from_settings(self) -> None: ...
    def shutdown_keep_awake(self) -> None: ...
