"""The contract the UI server expects from whatever orchestrates the agent.

Defined here (the consumer) so `ui_server` never imports `core` — keeping the
dependency graph one-directional: core → ui_server. Core's Orchestrator
satisfies this structurally.
"""
from __future__ import annotations

from collections.abc import Sequence
from typing import Any, Protocol

from pydantic import BaseModel


class OrchestratorAPI(Protocol):
    # Settings
    def get_settings(self) -> BaseModel: ...
    def update_settings(self, **fields: Any) -> BaseModel: ...

    # Capabilities
    def scan_capabilities(self) -> list[str]: ...

    # Lifecycle
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def is_running(self) -> bool: ...
    def status(self) -> dict[str, Any]: ...

    # Tasks
    def list_tasks(self) -> Sequence[BaseModel]: ...
    def get_task(self, task_id: str) -> BaseModel | None: ...
    def cancel_task(self, task_id: str) -> bool: ...
