"""Orchestrator API contract for the UI server."""
from __future__ import annotations

from collections.abc import Sequence
from typing import Any, Protocol

from pydantic import BaseModel


class OrchestratorAPI(Protocol):
    def get_settings(self) -> BaseModel: ...
    def update_settings(self, **fields: Any) -> BaseModel: ...
    def get_raw_settings_json(self) -> str: ...
    def save_raw_settings_json(self, text: str) -> BaseModel: ...

    def scan_capabilities(self) -> list[str]: ...
    def get_scan_state(self) -> dict[str, Any]: ...
    def start_background_scan(self) -> None: ...
    def rescan(self, *, restart_if_changed: bool = False) -> dict[str, Any]: ...
    def update_capability_policy(
        self,
        *,
        regular_disabled: list[str] | None = None,
        sensitive_allowed: list[str] | None = None,
        slavemode_allowed: list[str] | None = None,
    ) -> BaseModel: ...

    def start(self) -> None: ...
    def stop(self) -> None: ...
    def is_running(self) -> bool: ...
    def status(self) -> dict[str, Any]: ...
    def get_agent_logs(self, n: int = 100) -> list[str]: ...
    def register(self) -> str: ...

    def list_tasks(self) -> Sequence[BaseModel]: ...
    def get_task(self, task_id: str) -> BaseModel | None: ...
    def cancel_task(self, task_id: str) -> bool: ...
